### ISSUE TITLE
Сделать отдельный UI компонент для кнопки "Написать администратору"

### ISSUE THREAD

**Issue by vierim** [ya-pomogau/frontend-fork#126]
Исполнитель - @olgushe4ka 
Ревью - @vierim 

Нужно вынести кнопку "Написать администратору" (выпадающее меню в шапке) в отдельный UI компонент и добавить для нее неактивный статус (такой статус используется только в мобильной версии).

**Comment by AleksandrDronov** [comment]
Возьму эту задачку
