### ISSUE TITLE
Улучшение юзабилити карты заявок

### ISSUE THREAD

**Issue by vierim** [ya-pomogau/frontend-fork#85]
Исполнитель - @Gyxer513 
Ревью - @vierim 

Сейчас при клике на иконку заявки на карте всплывающий тултип просто отображается ниже иконки. Если иконка расположена низко, то часть информации на тултипе не видна - [https://disk.yandex.ru/i/YRLzwCgZ7xPB2w](https://disk.yandex.ru/i/YRLzwCgZ7xPB2w)

В идеале, при клике на иконку рассчитывать, помещается ли тултип в видимой части экрана (на десктопе и на телефоне) и если не помещается, то выполнять какое-то перемещение карты, чтобы тултип был виден сразу весь.

**Comment by Zdthns** [comment]
Не вижу смысла  в данном улучшении, так как карта двигается с помощью курсора в любом направлении
