### ISSUE TITLE
Прокинуть кнопку настройки профиля в сторибук компонента UserInfo

### ISSUE THREAD

**Issue by vierim** [ya-pomogau/frontend-fork#90]
Исполнитель - @olgushe4ka 
Ревью - @vierim 

Сейчас в сторибук http://localhost:6006/?path=/docs/entities-userinfo--docs нигде не отображается кнопка настройки профиля. Нужно это исправить, чтобы пример компонента в сторибуке соответствовал макету и текущей логике.

**Comment by olgushe4ka** [comment]
Сейчас кнопка настройки отображается только у аутенифированных рользователей. 
Я придумала только то, что чтобы это отображалось в Сторибук, надо в InfoContainer параметр isAuth выводить в пропс, а сейчас оно берется из стора.
Как это сделать в самом сторибуке, что как-будто пользователь зарегистирован, я не смогла разобраться :(
